## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Создать вектор размера 10, заполненный единицами

In [3]:
np.array([1 for _ in range(10)])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Создать вектор размера 10, заполненный числом 2.5

In [4]:
np.array([2.5 for _ in range(10)])

array([ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [9]:
a = np.zeros(10)
a[4] = 1
a

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

Развернуть вектор (первый становится последним)

In [98]:
a = np.arange(9)
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [96]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [69]:
for i,x in enumerate([1,2,0,0,4,0]):
    if x>0: print i

0
1
4


Создать 3x3 единичную матрицу

In [78]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Создать массив 3x3x3 со случайными значениями

In [87]:
np.random.randint(1,10,(3,3,3))

array([[[3, 5, 5],
        [7, 6, 1],
        [7, 1, 4]],

       [[5, 2, 5],
        [5, 5, 4],
        [4, 9, 5]],

       [[4, 1, 3],
        [7, 6, 8],
        [5, 3, 5]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [88]:
np.random.randint(1,10,(30)).mean()

5.0666666666666664

Перемножить матрицы 5x3 и 3x2

In [86]:
np.dot(np.random.randint(1,10,(5,3)),np.random.randint(1,10,(3,2)))

array([[ 83, 106],
       [110, 138],
       [ 56,  72],
       [100, 126],
       [ 89, 110]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [101]:
a = np.linspace(0,1,12)[1:11]
a

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

Заменить максимальный элемент на ноль

In [102]:
a[a.argmax()]=0
a

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.        ])

Преобразовать массив из float в int

In [103]:
np.around(np.random.random(10), decimals=0).astype(int)

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [143]:
a = np.random.random((10,2))
b = [[0 for i in range(10)] for j in range(10)]
for i in range(10):
    for j in range(10):
        b[i][j] = math.sqrt((a[i][0]-a[j][0])**2+(a[i][1]-a[j][1])**2)
print(b)

[[0.0, 0.41946334430496707, 0.7753348935597464, 0.6362426682156589, 0.33350414876136336, 0.9843052796008482, 0.4509170561892657, 0.3532195563168784, 0.49618066312743886, 0.5584712368494086], [0.41946334430496707, 0.0, 0.49255374671872626, 0.46721759657248874, 0.42500260462318296, 0.663510376168092, 0.22852509462684642, 0.13256692651711013, 0.07805305649902301, 0.22296238754163986], [0.7753348935597464, 0.49255374671872626, 0.0, 0.2065918390289161, 0.5272774352108489, 0.2149673144055541, 0.32783465959785235, 0.4514212523894117, 0.4787825813161539, 0.26968495542942594], [0.6362426682156589, 0.46721759657248874, 0.2065918390289161, 0.0, 0.34384989439703256, 0.4104019204004339, 0.24412676511690262, 0.374970945633381, 0.48689250992239674, 0.28389825272395575], [0.33350414876136336, 0.42500260462318296, 0.5272774352108489, 0.34384989439703256, 0.0, 0.7417177049866068, 0.2752690947579711, 0.29325612169688475, 0.4910113497493267, 0.4104037326377179], [0.9843052796008482, 0.663510376168092, 0.2

Случайно расположить p элементов в 2D массив

In [151]:
import math
p = 9
s = int(math.sqrt(p))
a = np.random.random(p)
np.random.choice(a,p).reshape(s,s)

array([[ 0.87228928,  0.87228928,  0.06727769],
       [ 0.80759439,  0.17062329,  0.17062329],
       [ 0.17062329,  0.67409722,  0.06727769]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [155]:
a = np.array([1,2,3,4,5])
b = []
for i in a:
    b.append(i)
    for j in range(3): b.append(0)
np.array(b[:-3])

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

Найти наиболее частое значение в массиве

In [161]:
a = np.random.randint(1,10,(20))
print(a)
counts = np.bincount(a)
print(np.argmax(counts))

[5 2 9 3 7 8 2 4 7 7 7 4 9 4 7 2 1 7 8 9]
7


Найти n наибольших значений в массиве

In [199]:
n = 5
a = np.random.randint(1,10,(20))
print(a)
ind = np.argpartition(a, -n)[-n:]
print(a[ind])

[8 3 7 5 5 6 1 4 4 2 5 4 6 8 3 5 1 9 4 4]
[6 7 8 9 8]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [2]:
import pandas as pd
df = pd.read_csv('en.openfoodfacts.org.products.tsv', sep='\t', low_memory=False)

Посмотреть первые 5 записей

In [3]:
df.head()

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [6]:
len(df.index)

356027

Сколько столбцов в наборе данных?

In [7]:
len(df.columns)

163

Напечатайте все названия столбцов

In [8]:
df.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [11]:
df.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [13]:
df['-glucose_100g'].dtype

dtype('float64')

Как проиндексирован набор данных?

In [14]:
df.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [19]:
#  Считаю с 0
df[18:19]

code                                                url  \
18  0000000018197  http://world-en.openfoodfacts.org/product/0000...   

            creator   created_t      created_datetime last_modified_t  \
18  usda-ndb-import  1489055652  2017-03-09T10:34:12Z      1489055652   

   last_modified_datetime                      product_name generic_name  \
18   2017-03-09T10:34:12Z  Lotus Organic Brown Jasmine Rice          NaN   

   quantity         ...         fruits-vegetables-nuts_100g  \
18      NaN         ...                                 NaN   

   fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
18                                  NaN                              NaN   

   cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
18        NaN             NaN                   NaN                     NaN   

   nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
18                     NaN                 NaN                 NaN  

[1 rows x 163 columns]

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [90]:
chipo = pd.read_csv('chipotle.tsv.txt', sep='\t', low_memory=False)

Как много продуктов стоят более чем $10.00?

In [91]:
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype('float')
print(chipo.head())
chipo[chipo.item_price > 10.00].count()['item_price']

   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  


1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [96]:
chipo[['item_name','item_price']]

item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito        8.49
17                          Chicken Burrito        8.49
18                              Canned Soda        2.18
19                             Chicken Bowl        8.75
20                      Chips and Guacamole        4.45
21                         Barbacoa Burrito        8.99
22                         Nantucket Nectar        3.39
23                          Chicken Burrito       10.98
24                                     Izze        3.39
25             Chips and Fresh Tomato Salsa        2.39
26                             Chicken Bowl        8.49
27                         Carnitas Burrito        8.99
28                              Canned Soda        1.09
29                          Chicken Burrito        8.49
...                                     ...         ...
4592                       Barbacoa Burrito       11.75
4593                          Carnitas Bowl       11.75
4594                          Barbacoa Bowl       11.75
4595                           Chicken Bowl        8.75
4596                    Chips and Guacamole        4.45
4597                      Canned Soft Drink        1.25
4598                          Bottled Water        1.50
4599                           Chicken Bowl        8.75
4600                    Chips and Guacamole        4.45
4601                      Canned Soft Drink        1.25
4602                       Barbacoa Burrito        9.25
4603                       Barbacoa Burrito        9.25
4604                           Chicken Bowl        8.75
4605                    Chips and Guacamole        4.45
4606                      Canned Soft Drink        1.25
4607                          Steak Burrito       11.75
4608                         Veggie Burrito       11.25
4609                      Canned Soft Drink        1.25
4610                          Steak Burrito       11.75
4611                         Veggie Burrito       11.25
4612                          Carnitas Bowl        9.25
4613                                  Chips        2.15
4614                          Bottled Water        1.50
4615                     Chicken Soft Tacos        8.75
4616                    Chips and Guacamole        4.45
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [97]:
chipo.sort_values('item_name')

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description  item_price  
3389                                        [Diet Coke]       12.98  
341                                         [Diet Coke]        6.49  
1849                                             [Coke]        6.49  
1860                                        [Diet Coke]        6.49  
2713                                             [Coke]        6.49  
3422                                             [Coke]        6.49  
553                                         [Diet Coke]        6.49  
1916                                        [Diet Coke]        6.49  
1922                                             [Coke]        6.49  
1937                                        [Diet Coke]        6.49  
3836                                             [Coke]        6.49  
298                                            [Sprite]        6.49  
1976                                        [Diet Coke]        6.49  
1167                                             [Coke]        6.49  
3875                                     

Сколько было заказано самого дорогого предмета?

In [111]:
#  1) Находим индекс самого дорого предмета, выделяем его имя
#  2) Определяем длину выборки предметов с найденным в первом шаге именем
len(chipo[(chipo['item_name'] == chipo.iloc[chipo['item_price'].idxmax()]['item_name'])])

110

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [110]:
print(chipo['item_name'].eq('Veggie Salad Bowl').sum())

18


Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [109]:
len(chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)])

20